inputDataDir: /Users/j9/Desktop/fetch-socrata-fields/output/
inputConfigDir: /Users/j9/Desktop/fetch-socrata-fields/configs/
socrata_client_config_fname: socrata_config.yaml
log_dir: /Users/j9/Desktop/fetch-socrata-fields/logs/
exception_logfile: exception.log
src_records_cnt_field: SrcRecordsCnt
dataset_records_cnt_field: DatasetRecordsCnt
fourXFour: fourXFour
row_id_field: row_id
isLoaded: isLoaded
datasets_to_load_fn: datasets_to_load.csv
dataset_name_field: Socrata Dataset Name
dataset_src_dir_field:  Dataset_Source_Dir
dataset_src_fn_field: Dataset Source Filename
